config/routes.rb
Rails.application.routes.draw do


   root 'top#index'
   get'home/about' => 'top#about' ,as: 'top_about'

   get'users/:id/home' => 'users#home' ,as: 'users_home'


   devise_for :users

   resources :users, only: [:index, :edit, :show,:update]
   	resources :books

   resources :top, only: [:index]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

    validates :title, presence: true

    validates :body, presence: true
	validates :body, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true
  validates :name, length: { in: 2..20 }

  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def after_sign_up_path_for(resource)
  	user_path(resource)
  end
  def after_sign_in_path_for(resource)
  	user_path(resource)
  end
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
 def index
  	@books = Book.all
  	@book = Book.new
    @user = current_user
  end

  def show
  	@books = Book.find(params[:id])
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
    @books = Book.all
      @user = current_user
      render 'index'
    end
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user_id == current_user.id
    else
       redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    book = Book.find(params[:id])
      book.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to books_path
  end


  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!


  def index
    @users = User.all
    @book = Book.new
    @user =  current_user
  end

    def home
    @book = Book.new
    @books = Book.all
    @users = current_user
    @user = User.find(params[:id])
  end

  def show
    @book = Book.new
    @books = Book.all
    @user = User.find(params[:id])
  end


  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
    else
    redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_sidebar.html.erb
<% if book.errors.any?  %>
  <div style="color: red;" id="error_explanation">
    <h2 ><%= book.errors.count %>errors prohibited this obj from being saved:</h2>

    <ul>
    <% book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<h2>User info</h2>


  <%= attachment_image_tag user, :profile_image,:fill, 80, 80, fallback: "no_image.jpg"%>
  <div>
    name <%= user.name %>
  </div>
  <div>
    introduction <%= user.introduction%>
  </div>
      <% if current_user.id == user.id %>
        <%= link_to edit_user_path(current_user.id) do %>
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        <% end %>
      <% else %>
                <%= link_to user_path(current_user.id) do %>
        <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
        <% end %>
      <% end %>


<div><h2>New book</h2></div>




<%= form_for book do |f| %>

    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Opinion</h4>
    <%= f.text_area :body %>
      <div><%= f.submit 'Create Book' %>
    </div>

<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any?  %>
  <div style="color: red;" id="error_explanation">
    <h2 ><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>

<% end %>
<%= form_for(@book) do |f| %>
    <h4 class="editing">Title</h4>
    <%= f.text_field :title %>
    <h4 class="editing">Opinion</h4>
    <%= f.text_area :body %>

    <p class="editing"><%= f.submit 'Update Book' %></p>
<% end %>
<p>
	<%= link_to "Show", book_path(@book.id) %>
	|
	<%= link_to "Back", books_path %>
</p>

app/views/books/index.html.erb
<div class="container">
	<div class="row">

	    <div class="col-xs-3" >
		<%= render 'books/sidebar', book: @book ,user: @user %>
		</div>


		<div class="col-xs-9" >
		<h1>Books</h1>

			<table class="table table-striped">
			<tr>
				<th></th><th>Title</th><th>Opinion</th>
			</tr>

			<% @books.each do |book| %>
			<tr>
				<td>
					<%= link_to user_path(book.user.id) do %>
					<%= attachment_image_tag book.user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg" %>
					<% end %>
				</td>
				<td>
					<%= link_to book_path(book) do%>
					<%= book.title %>
					<% end %>
				</td>
				<td><%= book.body %></td>
			</tr>
			<% end %>
		    </table>
	    </div>

    </div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">

	    <div class="col-xs-3" >
		<%= render 'books/sidebar', book: @book ,user: @books.user   %>
		</div>

		<div class="col-xs-9" >
			<h1>Book detail</h1>
			<table class="table table-striped">
				<tr>
					<td><%= attachment_image_tag @books.user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg"%></td>
					<td><%= @books.title %></td>
					<td class="title"></td>
					<td class="opinion"><%= @books.body %></td>

					<% if  @books.user_id == current_user.id %>
					<td><%= link_to "Edit", edit_book_path(@books.id) %></td>
					<td><%= link_to "Destroy", book_path(@books.id), method: :delete, "data-confirm" => "Are you sure？" %></td>
					<% end %>

					</tr>
			     	<td><%= link_to user_path(@books.user_id) do %>
			     			<%= @books.user.name %>
			     		</td>
			     		<% end %>

		    </table>
	    </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-inverse" style=" height: 60px;">
  <div class="navbar-header" >
    <h3 style="margin: 0px 30px; color: white;">Bookers</h3>
  </div>

<div class="container-fluid">
<nav class="collapse navbar-collapse" style="color: #808080;　line-height: 60px; ">
  <ul class="nav navbar-nav" style="float: right;">
  <% if user_signed_in? %>
      <li>
        <%= link_to user_path(current_user.id) do %><span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span>
        <% end %>
      </li>
      <li>
        <%= link_to users_path do %><span class="glyphicon glyphicon-user" aria-hidden="true"> Users</span>
        <% end %>
      </li>
      <li>
        <%= link_to books_path do%><span class="glyphicon glyphicon-book" aria-hidden="true"> Books</span>
        <% end %>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do%><span class="glyphicon glyphicon-log-out" aria-hidden="true"> logout</span>
        <% end %>
      </li>

    <% else %>
      <li class="">
        <%= link_to root_path do%><span class="glyphicon glyphicon-home" aria-hidden="true"> Home</span>
        <% end %>
      </li>
      <li class="">
        <%= link_to top_about_path do%><span class="glyphicon glyphicon-link" aria-hidden="true">about</span>
        <% end %>
      </li>
      <li class="">
        <%= link_to new_user_registration_path do%><span class="glyphicon glyphicon-edit" aria-hidden="true"> sign up</span>
        <% end %>
      </li>
      <li class="">
        <%= link_to new_user_session_path do%><span class="glyphicon glyphicon-log-in" aria-hidden="true">  login</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>
</div>
</div>

<% if flash[:notice] %>
  <p class="success"><%= flash[:notice] %></p>
<% end %>


    <%= yield %>
  </body>
</html>

app/views/top/about.html.erb
<h1>Welcome to Bookers!
CopyRight Infratop.inc</h1>

app/views/top/index.html.erb
<h1>welcome to Bookers !!
In Bookers,

you can share and exchange your opinions , inpressions , and emotions

about various books!</h1>

<%= link_to "Log in", new_user_session_path %>
<%= link_to "Sign up", new_user_registration_path %>

app/views/users/edit.html.erb
<h1>User info</h1>

<% if @user.errors.any?  %>
  <div style="color: red;" id="error_explanation">
    <h2 ><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <%= form_for(@user) do |f| %>

  	<div class="">Name <%= f.text_field :name, autofocus: true, placeholder:"名前"%></div>

	<div class="">Image</div>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    <div class="">Introduction <%= f.text_area :introduction, autofocus: true %></div>


    <%= f.submit "Update User" %>

   <% end %>

app/views/users/home.html.erb
<div class="container">
	<div class="row">

	    <div class="col-xs-3" >
			<%= render 'books/sidebar', book: @book ,user: @users %>
		</div>

		<div class="col-xs-9">
			<h1 class="head">Books</h1>

		<table class="table table-striped">
			<tr>
				<th></th><th>Title</th> <th>Opinion</th>
			</tr>

			<% @books.each do |book| %>
			<% if book.user_id == @user.id %>

			<tr>
				<td><%= attachment_image_tag @user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg"%></td>
				<td><%= link_to book_path(book.id) do%>
						<%= book.title %>
					<% end %>
				<td class="Opinion"><%= book.body %></td>
			</tr>
			<% end %>
			<% end %>
		</table>
	</div>
</div></div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">

	    <div class="col-xs-3" >

			<%= render 'books/sidebar', book: @book ,user: @user %>
		</div>

		<div class="col-xs-9" >
		<h2>Users</h2>

		<table class="table table-striped">
		<tr>
			<th>image</th><th>name</th> <th></th>
		</tr>

		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>
			<td><%= link_to 'Show', user_path(user) %></td>
		</tr>
		<% end %>
	    </table>
	    </div>
	 </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">

	    <div class="col-xs-3" >
			<%= render 'books/sidebar', book: @book ,user: @user %>
		</div>

		<div class="col-xs-9">
			<h1 class="head">Books</h1>

		<table class="table table-striped">
			<tr>
				<th></th><th>Title</th> <th>Opinion</th>
			</tr>

			<% @books.each do |book| %>
			<% if book.user_id == @user.id %>

			<tr>
				<td><%= attachment_image_tag @user, :profile_image,:fill, 50, 50, fallback: "no_image.jpg"%></td>
				<td><%= link_to book_path(book.id) do%>
						<%= book.title %>
					<% end %>
				<td class="Opinion"><%= book.body %></td>
			</tr>
			<% end %>
			<% end %>
		</table>
	</div>
</div></div>